# See config.example.yml for documentation.
object: orig/GZ3E70/sys/main.dol
hash: d804d3dd5b4ff5d215e1f3b6d39e9ebfc600655b
symbols: config/GZ3E70/symbols.txt
splits: config/GZ3E70/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 11